ifndef ROLLCOMPILER
  ROLLCOMPILER = gnu
endif
COMPILERNAME := $(firstword $(subst /, ,$(ROLLCOMPILER)))

ifndef ROLLMPI
  ROLLMPI = rocks-openmpi
endif
MPINAME := $(firstword $(subst /, ,$(ROLLMPI)))

NAME           = sdsc-tau_$(COMPILERNAME)_$(MPINAME)
VERSION        = 2.23
RELEASE        = 4
PKGROOT        = /opt/tau/$(COMPILERNAME)/$(MPINAME)

SRC_SUBDIR     = tau

SOURCE_NAME    = tau
SOURCE_SUFFIX  = tgz
SOURCE_VERSION = $(VERSION)
SOURCE_PKG     = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR     = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

BINUTILS_SOURCE_NAME    = binutils
BINUTILS_SOURCE_SUFFIX  = tar.gz
BINUTILS_SOURCE_VERSION = 2.23.2
BINUTILS_SOURCE_PKG     = $(BINUTILS_SOURCE_NAME)-$(BINUTILS_SOURCE_VERSION).$(BINUTILS_SOURCE_SUFFIX)
BINUTILS_SOURCE_DIR     = $(BINUTILS_SOURCE_PKG:%.$(BINUTILS_SOURCE_SUFFIX)=%)

TGZ_PKGS       = $(SOURCE_PKG)
TAR_GZ_PKGS    = $(BINUTILS_SOURCE_PKG)

RPM.EXTRAS     = AutoReq:No
