#%Module1.0
module-whatis "ipm"
module-whatis "Version: VERSION"
module-whatis "Description: ipm"
module-whatis "Compiler: COMPILERNAME"
module-whatis "MPI Flavors: ROLLMPI"
# Look for MPI flavor in LOADEDMODULES. If no MPI module is loaded, default to
# first element in ROLLMPI.
set mpi [lindex [split "ROLLMPI" "/ "] 0]
foreach {module} [split $::env(LOADEDMODULES) :] {
  set module [lindex [split $module /] 0]
  if {[regexp [format {%s(/|\s|$)} $module] "ROLLMPI"]} {
    set mpi $module
  }
}
setenv IPMHOME /opt/ipm/ROLLCOMPILER/$mpi
prepend-path PATH /opt/ipm/ROLLCOMPILER/$mpi/bin
setenv SDSC_IPM_BASE /opt/ipm/ROLLCOMPILER/$mpi
prepend-path LD_LIBRARY_PATH /opt/ipm/ROLLCOMPILER/$mpi/lib
module load papi mxml
