#%Module1.0
module-whatis "ipm"
module-whatis "Version: VERSION"
module-whatis "Description: ipm"
module-whatis "Compiler: COMPILERNAME"
module-whatis "MPI Flavors: ROLLMPI"
if {! [info exists ::env(MPIHOME)] || ! [info exists ::env(LOADEDMODULES)]} {
  puts stderr "Need to load an mpi module before loading fftw/VERSION"
  exit 1
}
foreach {x} [list ROLLMPI] {
  # Look for flavor in LOADEDMODULES, delimited by colon or end of string.
  # Can also be followed by / (version number).
  if {[regexp [format {(:|^)%s([:/]|$)} $x] $::env(LOADEDMODULES)]} {
    set mpi $x
    break
  }
}
if {! [info exists mpi]} {
  puts stderr "No supported MPI flavor found"
  exit 1
}
setenv IPMHOME /opt/ipm/ROLLCOMPILER/$mpi
prepend-path PATH /opt/ipm/ROLLCOMPILER/$mpi/bin
setenv SDSC_IPM_BASE /opt/ipm/ROLLCOMPILER/$mpi
prepend-path LD_LIBRARY_PATH /opt/ipm/ROLLCOMPILER/$mpi/lib
module load papi mxml
