#%Module1.0
module-whatis "tau"
module-whatis "Version: VERSION"
module-whatis "Description: tau"
module-whatis "Compiler: COMPILERNAME"
module-whatis "MPI Flavors: ROLLMPI"
if {! [info exists ::env(MPIHOME)] || ! [info exists ::env(LOADEDMODULES)]} {
  puts stderr "Need to load an mpi module before loading fftw/VERSION"
  exit 1
}
foreach {x} [list ROLLMPI] {
  # Look for flavor in LOADEDMODULES, delimited by colon or end of string.
  # Can also be followed by / (version number).
  if {[regexp [format {(:|^)%s([:/]|$)} $x] $::env(LOADEDMODULES)]} {
    set mpi $x
    break
  }
}
if {! [info exists mpi]} {
  puts stderr "No supported MPI flavor found"
  exit 1
}
prepend-path PATH /opt/tau/ROLLCOMPILER/$mpi/x86_64/bin
setenv TAU_BASE /opt/tau/ROLLCOMPILER/$mpi
setenv TAUHOME /opt/tau/ROLLCOMPILER/$mpi
prepend-path LD_LIBRARY_PATH /opt/tau/ROLLCOMPILER/$mpi/x86_64/lib
if { [string first "mvapich2" $mpi] >= 0 } {
  setenv TAU_LINKER_OPT17 -lmpl
}
module load papi pdt
