#%Module1.0
module-whatis "tau"
module-whatis "Version: VERSION"
module-whatis "Description: tau"
module-whatis "Compiler: COMPILERNAME"
module-whatis "MPI Flavors: ROLLMPI"
# Look for MPI flavor in LOADEDMODULES. If no MPI module is loaded, default to
# first element in ROLLMPI.
set mpi [lindex [split "ROLLMPI" "/ "] 0]
foreach {module} [split $::env(LOADEDMODULES) :] {
  set module [lindex [split $module /] 0]
  if {[regexp [format {%s(/|\s|$)} $module] "ROLLMPI"]} {
    set mpi $module
  }
}
prepend-path PATH /opt/tau/ROLLCOMPILER/$mpi/x86_64/bin
setenv TAU_BASE /opt/tau/ROLLCOMPILER/$mpi
setenv TAUHOME /opt/tau/ROLLCOMPILER/$mpi
prepend-path LD_LIBRARY_PATH /opt/tau/ROLLCOMPILER/$mpi/x86_64/lib
if { [string first "mvapich2" $mpi] >= 0 } {
  setenv TAU_LINKER_OPT17 -lmpl
}
module load papi pdt
